name: "Test cutomized print date and time action"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom date time action
        uses: nikolhodos/date-time-action@main
